server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: emc123456
    url: jdbc:mysql://115.120.215.88:3307/senior_community_server?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
#    在控制台打印SQL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
